// Auto generated by Craby. DO NOT EDIT.
#include <CxxCalculatorModule.hpp>
#include <CxxCrabyTestModule.hpp>
#include <ReactCommon/CxxTurboModuleUtils.h>
#include <jni.h>

jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::calculator::CxxCalculatorModule::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::calculator::CxxCalculatorModule>(jsInvoker);
    });
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::crabytest::CxxCrabyTestModule::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::crabytest::CxxCrabyTestModule>(jsInvoker);
    });
  return JNI_VERSION_1_6;
}

extern "C"
JNIEXPORT void JNICALL
Java_com_crabytest_CrabyTestPackage_nativeSetDataPath(JNIEnv *env, jclass clazz, jstring jDataPath) {
  auto dataPath = std::string(env->GetStringUTFChars(jDataPath, nullptr));
  craby::calculator::CxxCalculatorModule::dataPath = dataPath;
  craby::crabytest::CxxCrabyTestModule::dataPath = dataPath;
}
