/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function build(opts: BuildOptions): void

export interface BuildOptions {
  projectRoot: string
}

export declare function clean(opts: CleanOptions): void

export interface CleanOptions {
  projectRoot: string
}

export declare function codegen(opts: CodegenOptions): void

export interface CodegenOptions {
  projectRoot: string
  overwrite: boolean
}

export declare function debug(message: string): void

export declare function doctor(opts: DoctorOptions): void

export interface DoctorOptions {
  projectRoot: string
}

export declare function error(message: string): void

export declare function info(message: string): void

export declare function init(opts: InitOptions): void

export interface InitOptions {
  cwd: string
  pkgName: string
}

export declare function setup(levelFilter?: string | undefined | null): void

export declare function show(opts: ShowOptions): void

export interface ShowOptions {
  projectRoot: string
}

export declare function trace(message: string): void

export declare function warn(message: string): void
