compressionLevel: mixed

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - x64
    - ia32
    - arm64
    - arm
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32
