// Auto generated by Craby. DO NOT EDIT.
use std::os::raw::*;
use craby_core::ios::interop::string::*;

#[no_mangle]
pub extern "C" fn numericMethod(arg: c_double) -> c_double {
    basic_module::basic::numeric_method(arg)
}

#[no_mangle]
pub extern "C" fn booleanMethod(arg: bool) -> bool {
    basic_module::basic::boolean_method(arg)
}

#[no_mangle]
pub extern "C" fn stringMethod(arg: *const c_char) -> *const c_char {
    let arg = String::from_native(arg).unwrap();
    let ret = basic_module::basic::string_method(arg);
    ret.to_native().unwrap()
}
