// Auto generated by Craby. DO NOT EDIT.
pub mod basic {
    use crate::impls;

    pub fn numeric_method(arg: f64) -> f64 {
        impls::numeric_method(arg)
    }

    pub fn boolean_method(arg: bool) -> bool {
        impls::boolean_method(arg)
    }

    pub fn string_method(arg: String) -> String {
        impls::string_method(arg)
    }
}

mod impls;
