// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::{{ flat_name }}::bridging")]
pub mod bridging {
    extern "Rust" {
    }
}
