// Auto generated by Craby. DO NOT EDIT.
#include "{{ cxx_name }}.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace {{ flat_name }} {
namespace modules {

std::string {{ cxx_name }}::dataPath = std::string();

{{ cxx_name }}::{{ cxx_name }}(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule({{ cxx_name }}::kModuleName, jsInvoker) {
}

{{ cxx_name }}::~{{ cxx_name }}() {
}

} // namespace modules
} // namespace {{ flat_name }}
} // namespace craby
