// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include <memory>
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>

namespace craby {
namespace {{ flat_name }} {
namespace modules {

class JSI_EXPORT {{ cxx_name }} : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "{{ pascal_name }}";

  {{ cxx_name }}(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);
  ~{{ cxx_name }}();

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
};

} // namespace modules
} // namespace {{ flat_name }}
} // namespace craby
