// Auto generated by Craby. DO NOT EDIT.
pub struct Context {
    pub id: usize,
    pub data_path: String,
}

impl Context {
    pub fn new(id: usize, data_path: &str) -> Self {
        Context { id, data_path: data_path.to_string() }
    }
}
