// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use crate::calculator_impl::*;
use crate::craby_test_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::bridging")]
pub mod bridging {
    struct NullableNumber {
        null: bool,
        val: f64,
    }

    struct NullableString {
        null: bool,
        val: String
    }

    struct SubObject {
        a: NullableString,
        b: f64,
        c: bool,
    }

    struct NullableSubObject {
        null: bool,
        val: SubObject
    }

    struct TestObject {
        foo: String,
        bar: f64,
        baz: bool,
        sub: NullableSubObject,
        camel_case: f64,
        pascal_case: f64,
        snake_case: f64,
    }

    enum MyEnum {
        Foo,
        Bar,
        Baz,
    }

    enum SwitchState {
        Off,
        On,
    }

    extern "Rust" {
        #[cxx_name = "add"]
        fn calculator_add(id_: usize, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "subtract"]
        fn calculator_subtract(id_: usize, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "multiply"]
        fn calculator_multiply(id_: usize, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "divide"]
        fn calculator_divide(id_: usize, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "numericMethod"]
        fn craby_test_numeric_method(id_: usize, arg: f64) -> Result<f64>;

        #[cxx_name = "booleanMethod"]
        fn craby_test_boolean_method(id_: usize, arg: bool) -> Result<bool>;

        #[cxx_name = "stringMethod"]
        fn craby_test_string_method(id_: usize, arg: String) -> Result<String>;

        #[cxx_name = "objectMethod"]
        fn craby_test_object_method(id_: usize, arg: TestObject) -> Result<TestObject>;

        #[cxx_name = "arrayMethod"]
        fn craby_test_array_method(id_: usize, arg: Vec<f64>) -> Result<Vec<f64>>;

        #[cxx_name = "enumMethod"]
        fn craby_test_enum_method(id_: usize, arg_0: MyEnum, arg_1: SwitchState) -> Result<String>;

        #[cxx_name = "nullableMethod"]
        fn craby_test_nullable_method(id_: usize, arg: NullableNumber) -> Result<NullableNumber>;

        #[cxx_name = "promiseMethod"]
        fn craby_test_promise_method(id_: usize, arg: f64) -> Result<f64>;

        #[cxx_name = "camelMethod"]
        fn craby_test_camel_method(id_: usize) -> Result<()>;

        #[cxx_name = "pascalMethod"]
        fn craby_test_pascal_method(id_: usize) -> Result<()>;

        #[cxx_name = "snakeMethod"]
        fn craby_test_snake_method(id_: usize) -> Result<()>;

        #[cxx_name = "triggerSignal"]
        fn craby_test_trigger_signal(id_: usize) -> Result<()>;
    }

    #[namespace = "craby::signals"]
    unsafe extern "C++" {
        include!("signals.h");

        type SignalManager;

        fn emit(self: &SignalManager, id: usize, name: &str);
        #[rust_name = "get_signal_manager"]
        fn getSignalManager() -> &'static SignalManager;
    }
}

fn calculator_add(id_: usize, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    catch_panic!({
        let it = Calculator::new(id_);
        let ret = it.add(a, b);
        ret
    })
}

fn calculator_subtract(id_: usize, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    catch_panic!({
        let it = Calculator::new(id_);
        let ret = it.subtract(a, b);
        ret
    })
}

fn calculator_multiply(id_: usize, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    catch_panic!({
        let it = Calculator::new(id_);
        let ret = it.multiply(a, b);
        ret
    })
}

fn calculator_divide(id_: usize, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    catch_panic!({
        let it = Calculator::new(id_);
        let ret = it.divide(a, b);
        ret
    })
}

fn craby_test_numeric_method(id_: usize, arg: f64) -> Result<f64, anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.numeric_method(arg);
        ret
    })
}

fn craby_test_boolean_method(id_: usize, arg: bool) -> Result<bool, anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.boolean_method(arg);
        ret
    })
}

fn craby_test_string_method(id_: usize, arg: String) -> Result<String, anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.string_method(arg);
        ret
    })
}

fn craby_test_object_method(id_: usize, arg: TestObject) -> Result<TestObject, anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.object_method(arg);
        ret
    })
}

fn craby_test_array_method(id_: usize, arg: Vec<f64>) -> Result<Vec<f64>, anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.array_method(arg);
        ret
    })
}

fn craby_test_enum_method(id_: usize, arg_0: MyEnum, arg_1: SwitchState) -> Result<String, anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.enum_method(arg_0, arg_1);
        ret
    })
}

fn craby_test_nullable_method(id_: usize, arg: NullableNumber) -> Result<NullableNumber, anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.nullable_method(arg.into());
        ret.into()
    })
}

fn craby_test_promise_method(id_: usize, arg: f64) -> Result<f64, anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.promise_method(arg);
        ret
    }).and_then(|r| r)
}

fn craby_test_camel_method(id_: usize) -> Result<(), anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.camel_method();
        ret
    })
}

fn craby_test_pascal_method(id_: usize) -> Result<(), anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.pascal_method();
        ret
    })
}

fn craby_test_snake_method(id_: usize) -> Result<(), anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.snake_method();
        ret
    })
}

fn craby_test_trigger_signal(id_: usize) -> Result<(), anyhow::Error> {
    catch_panic!({
        let it = CrabyTest::new(id_);
        let ret = it.trigger_signal();
        ret
    })
}
