// Auto generated by Craby. DO NOT EDIT.
use craby_core::jni::sys::*;
use craby_core::jni::{objects::JObject, JNIEnv};
use craby_core::android::interop::string::*;

#[no_mangle]
pub extern "C" fn Java_com_basic_BasicModule_nativeNumericMethod(_env: JNIEnv, _class: JObject, arg: jdouble) -> jdouble {
    basic_module::basic::numeric_method(arg)
}

#[no_mangle]
pub extern "C" fn Java_com_basic_BasicModule_nativeBooleanMethod(_env: JNIEnv, _class: JObject, arg: bool) -> bool {
    basic_module::basic::boolean_method(arg)
}

#[no_mangle]
pub extern "C" fn Java_com_basic_BasicModule_nativeStringMethod(mut env: JNIEnv, _class: JObject, arg: jstring) -> jstring {
    let arg = String::from_native(arg, &mut env).unwrap();
    let ret = basic_module::basic::string_method(arg);
    ret.to_native(&mut env).unwrap()
}
